#!/usr/bin/python
import os
import sys

app_path = os.path.abspath(os.path.dirname(__file__))
if not app_path in sys.path:
    sys.path.append(app_path)


virtenv = os.environ['OPENSHIFT_PYTHON_DIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass


from barbara import app
application = app
